#define ZR_VER_PRODUCT_NAME     "Zombie:Reloaded"
#define ZR_VER_COPYRIGHT        "Copyright (C) 2009-2012  Greyscale, Richard Helgeby"
#define ZR_VER_VERSION          VERSION
#define ZR_VER_BRANCH           "zr-3.0-b2"
#define ZR_VER_REVISION         "Unofficial build - based on 693:ba1afee95fd5"
#define ZR_VER_LICENSE          "GNU GPL, Version 3"
#define ZR_VER_DATE             "Wed, 04 Jul 2012 17:09:44 +0200"
